#!/usr/bin/env bash
# Optional host DNS for a private zone (default lab uses sslip.io instead).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/lib.sh"
load_config

usage() {
  cat <<EOF
Usage: $(basename "$0")

DNS_MODE=${DNS_MODE}

  sslip     (default) no local DNS daemon; names use ${SNO_IP}.sslip.io
  dnsmasq   write a dnsmasq snippet for ${CLUSTER_FQDN} on ${HOST_IP}
  hosts     print /etc/hosts lines (wildcard apps will still need dnsmasq/sslip)

EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

case "${DNS_MODE}" in
  sslip)
    log "Using sslip.io; public DNS must resolve:"
    echo "  api.${CLUSTER_FQDN} -> ${SNO_IP}"
    echo "  api-int.${CLUSTER_FQDN} -> ${SNO_IP}"
    echo "  *.apps.${CLUSTER_FQDN} -> ${SNO_IP}"
    echo "  ${SNO_HOSTNAME} -> ${SNO_IP}"
    ;;
  hosts)
    cat <<EOF
# Add to /etc/hosts (wildcard *.apps will NOT work this way):
${SNO_IP} api.${CLUSTER_FQDN} api-int.${CLUSTER_FQDN} ${SNO_HOSTNAME} console-openshift-console.apps.${CLUSTER_FQDN} oauth-openshift.apps.${CLUSTER_FQDN}
EOF
    ;;
  dnsmasq)
    command -v dnsmasq >/dev/null 2>&1 || die "dnsmasq is not installed"
    conf="${OUTPUT_DIR}/dnsmasq-okd-sno.conf"
    mkdir -p "${OUTPUT_DIR}"
    cat >"${conf}" <<EOF
# Generated by scripts/setup-dns.sh
listen-address=${HOST_IP}
bind-interfaces
no-resolv
server=8.8.8.8
address=/${CLUSTER_FQDN}/${SNO_IP}
ptr-record=$(printf '%s' "${SNO_IP}" | awk -F. '{print $4"."$3"."$2"."$1}').in-addr.arpa,${SNO_HOSTNAME}
EOF
    log "Wrote ${conf}"
    log "Start with: sudo dnsmasq --conf-file=${conf} --no-daemon"
    log "Point the VM DNS at ${HOST_IP} (set in config.local.env) if you use this mode."
    ;;
  *)
    die "Unknown DNS_MODE=${DNS_MODE} (sslip|dnsmasq|hosts)"
    ;;
esac
